### ISSUE TITLE
open MemoryByteChannel.newByteChannel() readable if not specified

### ISSUE THREAD

**Issue by miraculix0815** [SylvainJuge/memoryfs#2]
Hello Sylvian,

while opening an InputStream i got an IllegalArgumentException: "exactly one of read or write expected, mutualy exclusive"

please add a StandardOpenOption.READ if no option is given as stated in the doc of Files.newByteChannel(Path path, Set<? extends OpenOption> options, FileAttribute<?>... attrs) throws IOException

cite: "... If neither option (or the APPEND option) is present then the file is opened for reading."

The call stack of the Exception is as follows
sylvain.juge.memoryfs.MemoryFileSystem.newByteChannel(
sylvain.juge.memoryfs.MemoryFileSystemProvider.newByteChannel(
java.nio.file.Files.newByteChannel(
java.nio.file.Files.newByteChannel(
java.nio.file.spi.FileSystemProvider.newInputStream(
java.nio.file.Files.newInputStream(

Thanks in advance.
Jan

**Comment by SylvainJuge** [comment]
Yes, that's clearly a bug since it does not fit the API specification.

It makes sense to default to READ when no READ or WRITE option is provided, but the javadoc is probalby too specific with APPEND.

Unless combined with WRITE, APPEND have to be ignored, as does TRUNCATE_EXISTING and CREATE or CREATE_NEW (but the javadoc does not mention them).
