### ISSUE TITLE
Files.readAllLines(p, Charset.defaultCharset()) delivers content on emtpy files

### ISSUE THREAD

**Issue by miraculix0815** [SylvainJuge/memoryfs#6]
Hello Sylvain,

the issue is easy to test:

assertThat(Files.size(p)).isEqualTo(0); // ok
assertThat(Files.readAllBytes(p)).isEmpty(); // ok
assertThat(Files.readAllLines(p, Charset.defaultCharset())).isEmpty(); // fails

maybe it has something to do with encoding and/or buffer size. The big issue is, that readAllLines delivers more lines than writeAllLines has written to that file.

Regards, Jan

**Comment by SylvainJuge** [comment]
That's weird, and I bet it have something to do with the fact that the file data is stored as a simple byte array full of zeroes by default.
I have been able to debug this up to Channels.ReadableByteChannelImpl.read(...), but I really miss the jdk debug symbols so it might take some time to find why it behaves this way.

**Comment by miraculix0815** [comment]
I think, I start to understand. ReadableByteChannelImpl.read() doesn't
care for a size other than the length of the backing ByteArray. I think
it might help to return -1 in MemoryByteChannel.read if position is
greater than data.size().

I found a simpler setup to reproduce the bug without character encoding
and stuff:

byte[] b = new byte[1]; // write at least one byte
Files.write(p, b);      // for the creation of the backing array
assertThat(Files.readAllBytes(p)).isEqualTo(b);
// see the complete array (int[32])

Hope that helps.

**Comment by SylvainJuge** [comment]
Thanks for the debugging, I finally found where the bug was.

As you discovered, when we read file lines, we use an input stream, and jdk classes don't rely on actual content size, which is normal since most streams don't have any size at all.

In class **FileData**, we create an input stream from byte array, and I wasn't using the correct constructor with size, thus the inputstream behaved like empty array was actual file data.
