### ISSUE TITLE
Files.createDirectories(fs.getPath("test")) throws NPE

### ISSUE THREAD

**Issue by miraculix0815** [SylvainJuge/memoryfs#7]
Hello Sylvain,

Files.createDirectories(fs.getPath("test")) throws NPE but should be resolved against "/" or some default path to be consistent with Files.createFile(fs.getPath("test"));

Regards, Jan

**Comment by SylvainJuge** [comment]
Hi Jan,

Thanks again for the bug report.
The issue lies within the MemoryFileSystem.createEntry(...) since we rely on path without converting it first to an absolute path.

There are a lot of such corner cases where current impelementation does not really behave like default fs implementation. It may be a good idea to start writing a test suite able to execute such scenarios on different fs implementations in order to make sure that we have a consistent behavior.

There is probably something useful within openjdk sources, if there is such "user-level filesystem behavior test" that would be perfect !!

**Comment by miraculix0815** [comment]
> There is probably something useful within openjdk sources, if there is
> such "user-level filesystem behavior test" that would be perfect !!

I didn't found anything. I posted a question on nio-dev@openjdk.java.net
with the title "conformance check for user file systems". Lets see ...

**Comment by SylvainJuge** [comment]
I haven't found anything either, 

however, I've switched my tests to use more the Files.xxx static methods to be closer to what end-user calls (instead of relying directly on implementation). I've found few bugs and it could be made possible to make such assertions generic enough to be portable to another implementation since it is almost not coupled with actual impl.

**Comment by miraculix0815** [comment]
Am 19.11.2013 16:23, schrieb SylvainJuge:

> I haven't found anything either,
> 
> however, I've switched my tests to use more the Files.xxx static methods
> to be closer to what end-user calls (instead of relying directly on
> implementation). I've found few bugs and it could be made possible to
> make such assertions generic enough to be portable to another
> implementation since it is almost not coupled with actual impl.

LOL, Alan Bateman answered to the question for a "conformance test
suite" on nio-dev@openjdk.java.net:

> There isn't but it would be a great project for someone to do. 

Maybe you can promote your test suite to the jdk?
